---
title: "Lab 03 - Nobel laureates"
author: "Jessie"
date: "1/24"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
```

## Exercises

### Exercise 1
Observations: 935, variables: 26, each row represents an observation.

```{r ex1}
glimpse(nobel)
```
### Exercise 2
```{r ex2}
nobel_living<-nobel
nobel_living<- nobel_living %>% filter( !is.na(country), gender!="org", is.na(died_date)) 
```

### Exercise 3
According to the bar plot, the title is true for economics and medicine. But still over half of the noble prize owners are based in the U.S. in the field of chemistry and physics.
```{r ex3}
nobel_living <- nobel_living %>%
  mutate(
    country_us = if_else(country == "USA", "USA", "Other")
  )
nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))
ggplot(nobel_living_science, aes(x=country_us, fill=category)) + 
  geom_bar() +
  facet_wrap(~category, nrow=4)

```
### Exercise 4

...

### Exercise 5

...

### Exercise 6

...
